### ISSUE TITLE
using the available trained HMM model for speech-music discrimination

### ISSUE THREAD

**Issue by ardixiv** [tyiannak/pyAudioAnalysis#1]
playing around with your interesting project, I encountered an issue whilst trying to perform a HMM-based segmentation and classification, using the available trained HMM model for speech-music discrimination.

![image](https://cloud.githubusercontent.com/assets/2489127/7660616/fb2bbf1e-fb4b-11e4-9ae7-ce5488398c36.png)

note that I am running this on an EC2 server with only ssh access.

**Comment by tyiannak** [comment]
Thank you for your feedback. Can you please share the input wav file? This
is probably a bug under certain input circumstances and the input file will
probably help me to repair it.
Thank you again,
Theodore

-----
Theodoros Giannakopoulos
http://www.di.uoa.gr/~tyiannak

**Comment by shashank7099** [comment]
can you please tell  me how did you provide value of the variable to be trained in the csv file (arousal and valance) for regression training.
![capture151365135](https://cloud.githubusercontent.com/assets/16380841/11934797/416d911a-a82a-11e5-8f92-6ca4824e6ccf.PNG)

**Comment by tyiannak** [comment]
shashank7099, these are the ground truth values for each sample, therefore they correspond to human annotations.
