### ISSUE TITLE
scikits.talkbox should be listed in dependencies on the wiki page

### ISSUE THREAD

**Issue by shakdwipeea** [tyiannak/pyAudioAnalysis#10]
I had to install this module to use this library

I used pip to do that
 ` sudo pip install scikits.talkbox `

It is imported in [audioFeatureExtraction.py](https://github.com/tyiannak/pyAudioAnalysis/blob/master/audioFeatureExtraction.py#L22)

**Comment by tyiannak** [comment]
Thanx alot it's been added!
