### ISSUE TITLE
Import Error- No module named eyeD3

### ISSUE THREAD

**Issue by joyjitchatterjee** [tyiannak/pyAudioAnalysis#111]
I am trying to use pyAudioAnalysis but am facing an issue for long i.e. no module named eyeD3. I have all libraries ( including eyeD3) already installed and there isn't any directory issue probably. I am using Python 2.7.13 for the purpose. from pyAudioAnalysis import XYZ whatever I write here, it shows import error in eyeD3. Would be glad for your help in this regard.

**Comment by The-Gupta** [comment]
I randomly installed **eyed3==0.7.11** (pip install eyed3==0.7.11) and it works just fine for me. 
I tried to follow the author's comment [here](https://github.com/tyiannak/pyAudioAnalysis/issues/2) - 

> An update: please use the latest library version, and install eyed3 using pip (see wiki and README for instructions).

but importing always killed the kernel (on Anaconda), and I could not fix that

**Comment by jacquesbessa** [comment]
eyed3 is in lib/site-packages correcty?

**Comment by sateesh-p** [comment]
That's not my issue.I posted issue no. 115

**Comment by sateesh-p** [comment]
Sry I raised issue no. #230

**Comment by armaan115** [comment]
I had the same problem, but when I made the 'd' lowercase, it worked for me

![Annotation 2019-11-20 190603](https://user-images.githubusercontent.com/49625265/69300957-8cfdd980-0bc9-11ea-8e3e-79a2a2aaddec.png)

Also, I know this question is more than 2 years old, just trying to help out :)

**Comment by herve-guerin-pro** [comment]
The name of the module changed from eyeD3 to eyed3 sometime ago.
I changed "import eyeD3" into "import eyed3" and it fixed my problem
