### ISSUE TITLE
What data was used for trained the SVM classifier? 

### ISSUE THREAD

**Issue by irisyupingren** [tyiannak/pyAudioAnalysis#12]
I wonder which dataset was used for the default SVM model in the segmentation? I used some of my own data to train a new model but the results are not as good.

**Comment by irisyupingren** [comment]
The author answered that it was ~2000 speech 1-5s segments and ~2000 music 1-5s segments

**Comment by ShenggaoZhu** [comment]
Hi, this is a great library, and I am planning to use the SVM classifier directly in my project. May I know the classification accuracy of the provided SVM model? Thanks a lot!
