### ISSUE TITLE
TypeError: object of type 'numpy.float64' has no len()

### ISSUE THREAD

**Issue by manish-manghwani** [tyiannak/pyAudioAnalysis#126]
case 1:
Running script using php exec() function

`exec(
            '/home/manish/anaconda2/bin/python /opt/lampp/htdocs/frontend/master/python_features/audioAnalysis.py featureExtractionFile -i /opt/lampp/htdocs/frontend/master/python_features/input/testing.wav -mw 0.5 -ms 0.5 -sw 1 -ss 1 -o /opt/lampp/htdocs/frontend/master/python_features/output/1min_test 2>&1',$errout
            );
        var_dump($errout);`

Output :

array(13) {
  [0]=>
  string(60) " Error: file not found or other I/O error. (DECODING FAILED)"
  [1]=>
  string(34) "Traceback (most recent call last):"
  [2]=>
  string(98) "  File "/opt/lampp/htdocs/frontend/master/python_features/audioAnalysis.py", line 436, in <module>"
  [3]=>
  string(107) "    featureExtractionFileWrapper(args.input, args.output, args.mtwin, args.mtstep, args.stwin, args.ststep)"
  [4]=>
  string(117) "  File "/opt/lampp/htdocs/frontend/master/python_features/audioAnalysis.py", line 46, in featureExtractionFileWrapper"
  [5]=>
  string(102) "    aF.mtFeatureExtractionToFile(wavFileName, mtWin, mtStep, stWin, stStep, outFile, True, True, True)"
  [6]=>
  string(124) "  File "/opt/lampp/htdocs/frontend/master/python_features/audioFeatureExtraction.py", line 876, in mtFeatureExtractionToFile"
  [7]=>
  string(147) "    [mtF, stF] = mtFeatureExtraction(x, Fs, round(Fs * midTermSize), round(Fs * midTermStep), round(Fs * shortTermSize), round(Fs * shortTermStep))"
  [8]=>
  string(118) "  File "/opt/lampp/htdocs/frontend/master/python_features/audioFeatureExtraction.py", line 627, in mtFeatureExtraction"
  [9]=>
  string(63) "    stFeatures = stFeatureExtraction(signal, Fs, stWin, stStep)"
  [10]=>
  string(118) "  File "/opt/lampp/htdocs/frontend/master/python_features/audioFeatureExtraction.py", line 561, in stFeatureExtraction"
  [11]=>
  string(76) "    N = len(signal)                                # total number of samples"
  [12]=>
  string(54) "TypeError: object of type 'numpy.float64' has no len()"
}

Case 2 :

running same script from terminal 

`/home/manish/anaconda2/bin/python /opt/lampp/htdocs/frontend/master/python_features/audioAnalysis.py featureExtractionFile -i /opt/lampp/htdocs/frontend/master/python_features/input/testing.wav -mw 0.5 -ms 0.5 -sw 1 -ss 1 -o /opt/lampp/htdocs/frontend/master/python_features/output/1min_test`

Output:

Short-term CSV file: /opt/lampp/htdocs/frontend/master/python_features/output/1min_test_st.csv saved

**Comment by RayanWang** [comment]
According to 
[0]=>
string(60) " Error: file not found or other I/O error. (DECODING FAILED)", 
it's the file path related issue while running testing. Just modify "root_data_path" in script_tests.py.

**Comment by alecglen** [comment]
For others with this issue. I had the same thing but also a RunTimeWarning about not being able to find ffmpeg. Once I added it to my path, then this error also went away.
