### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by AhmedHamedTN** [tyiannak/pyAudioAnalysis#13]
- What are the prerequisites of using this library?

**My aim is to extract features from speech in an automatic way, meaning i want to have data from an FTP server as inputs in a programmatic way, shall i use PyAudioAnalysis with Django ?**
- Is there any full sample code so i can know exactly which steps come first ?

I am still new to python and to the audio analysis field but i need to get better since i need this for my Master thesis.

Thank you for your understanding.

**Comment by habbes** [comment]
I am very new to audio analysis. I want to use this library to test emotion detection or genre classification via a mobile app interface. I plan to use Flask to create the API for the mobile app to connect to. I think this is similar to what you want to achieve and I do not see why it shouldn't be possible. But I think the fact that models and samples have to be stored on local folders limits the application of the library when it comes to server-side deployment options.

**Comment by AhmedHamedTN** [comment]
Thank you for your reply @habbes , i thought this library would work for me since it works on folders and i am storing the audio in FTP so .. do you think i can be able to use the library within Django and make it work on the audio files i get from FTP ? Thank you.

**Comment by habbes** [comment]
@AhmedHamedTN, I think this library works with files and folders on the local filesystem. So if you fetch them from FTP and store them on the local file system (where your app is running) I guess it should work.
