### ISSUE TITLE
trainSVM_feature ERROR: No data found in any input folder!

### ISSUE THREAD

**Issue by MrLacuqer** [tyiannak/pyAudioAnalysis#158]
Hi all,
I'm trying to this tutorial: [link](http://rwx.io/blog/2016/04/08/bp-pyaudioanalysis/)
When I run this python code(createClassifierModel.py):
```
#!/usr/local/bin/python2
from pyAudioAnalysis import audioTrainTest as aT
import os
from sys import argv
script, dirname = argv

subdirectories = os.listdir(dirname)[:4]
subdirectories.pop(0)

subdirectories = [dirname + "/" + subDirName for subDirName in subdirectories]
#subdirectories = [dirname + subDirName for subDirName in subdirectories]

print(subdirectories)
aT.featureAndTrain(subdirectories, 1.0, 1.0, aT.shortTermWindow, aT.shortTermStep, "svm", "svmModel", False)
```
then, the result is:
```
$ python createClassifierModel.py trainingData/
['trainingData/breaking_glass', 'trainingData/vacuum']
Analyzing file 1 of 1: trainingData/breaking_glass/breaking_glass_02.wav
Analyzing file 1 of 1: trainingData/vacuum/apli-vacuummini.wav
trainSVM_feature ERROR: No data found in any input folder!
```

How Can I fix this error?
My folder tree is :
├── audioClassification
│   ├── pyAudioAnalysis
│   │   └── data
│   │       ├── beat
│   │       └── speechEmotion
│   ├── sampleData
│   └── trainingData
│       ├── breaking_glass/breaking_glass_02.wav
│       ├── bubbles/Bubbles.wav
│       └── vacuum/apli-vacuummini.wav

And my PC: Linux mint 18.3 Cinnamon 64-bit(Ubuntu 16.04)
the python version is: Python 2.7.12 (default, Dec  4 2017, 14:50:18)

Please help me.

Thanks.

**Comment by ksaye** [comment]
@Purdiding 

Did you ever resolve this?

**Comment by GaelCruz** [comment]
did anybody ever resolve?
