### ISSUE TITLE
Problems of Feature Extraction

### ISSUE THREAD

**Issue by zzhang68** [tyiannak/pyAudioAnalysis#17]
After I type the code for FeatureExtraction step and I got an error.
```
"audioFeatureExtraction.py", line 536, in stFeatureExtraction
    N = len(signal)                                # total number of samples
TypeError: object of type 'numpy.float64' has no len()
```
It says that this type does not have len().
Do you know how to fix it?

**Comment by AhmedHamedTN** [comment]
@zzhang68 Could you provide us with the code you wrote plz

**Comment by zzhang68** [comment]
@AhmedHamedTN  Sorry, I finally found out that there was something wrong with my audio path written in my code. I've solved that issue now, thanks for your reply!
