### ISSUE TITLE
ValueError during feature extraction

### ISSUE THREAD

**Issue by InnovArul** [tyiannak/pyAudioAnalysis#18]
Hello, I am facing ValueError during feature extraction. Is there anything I am missing to handle?

```
> Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
> [GCC 4.8.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from pyAudioAnalysis import audioBasicIO
> >>> from pyAudioAnalysis import audioFeatureExtraction
> >>> [Fs, x] = audioBasicIO.readAudioFile("./trainaudio/training80_43/39o1zJFeM7E.004.mp4.wav")
> >>> F = audioFeatureExtraction.stFeatureExtraction(x, Fs, 0.050*Fs, 0.025*Fs);
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "pyAudioAnalysis/audioFeatureExtraction.py", line 564, in stFeatureExtraction
>     curFV[2] = stEnergyEntropy(x)                    # short-term entropy of energy
>   File "pyAudioAnalysis/audioFeatureExtraction.py", line 48, in stEnergyEntropy
>     subWindows = frame.reshape(subWinLength, numOfShortBlocks, order='F').copy()
> ValueError: total size of new array must be unchanged
> >>> 
```

audio file: http://vocaroo.com/i/s0o0Hs3fZywG

**Comment by be4web** [comment]
I've had a similar problem. Looks as if stFeatureExtraction does not support stereo audio. I called
`audioBasicIO.stereo2mono(x)`
beforehand, although using numpy this: 
`x = np.mean(x, axis=1)`
maybe faster (I actually have no idea if this is true...).

**Comment by tyiannak** [comment]
Yes, stereo2mono() needs to be called after file reading to ensure that the signal is converted to mono. Feature extraction on stereo signals is not supported. However, if the information from two different channels actually have a conceptual meaning for your problem, you could try extract features on the two channels separately.
