### ISSUE TITLE
Perform file regression on descriptor file instead of audio file

### ISSUE THREAD

**Issue by NaturalFigurehead** [tyiannak/pyAudioAnalysis#183]
Is there a way to train a regression model, then perform single file regression on a descriptor file of an audio file instead of the actual audio file itself? 

My problem is that users will submit their audio files to me for analysis. I analyse them and send back the results. Then I delete the audio file because it's not mine and I can't store it. But if I can export some sort of descriptor file for that audio file, then later I'd like to be able to train a new model and compute the results for that descriptor file using regression. 

Is something like this possible with this library?

**Comment by tyiannak** [comment]
Yes it is possible but you will need to write your own wrapper for regression training that does not involve the audio I/O steps, since this will be done as a separate step.
