### ISSUE TITLE
"tuple index out of range" when training regression

### ISSUE THREAD

**Issue by NaturalFigurehead** [tyiannak/pyAudioAnalysis#184]
When I try to run `featureAndTrainRegression` I get this:
```
File "tbtrainer_regression.py", line 3, in <module>
    att.featureAndTrainRegression('wav',1.0,1.0,att.shortTermWindow,att.shortTermStep,'svm','mesto',True)
  File "/home/oliver/Documents/pyAudioAnalysis/pyAudioAnalysis/audioTrainTest.py", line 433, in featureAndTrainRegression
    numOfFeatures = featuresFinal[0].shape[1]
IndexError: tuple index out of range
```
This is after it finishes analyzing the 15 files in the directory. 
`featureAndTrain` works fine for me.

**Comment by NaturalFigurehead** [comment]
Yes there is two `.csv` documents. Maybe I'll try uploading an example repo of my project. I tried to follow the wiki exactly but I must be missing some minor detail.

**Comment by tyiannak** [comment]
Sure u could sent me some sample data also, there could also be a bug

**Comment by NaturalFigurehead** [comment]
Here's an example: https://github.com/NaturalFigurehead/regressionexample
Just run `python tbtrainer_regression.py` and it will start analyzing the included wav files.

**Comment by tyiannak** [comment]
I've checked it, it seems you have forgotten the ".wav" extension in the annotation files. Note that the name of the file needs to also contain the extension in each row of the csv file. I've also pushed an update with a warning when this is not the case

**Comment by NaturalFigurehead** [comment]
Ah yep that worked for me. Looks like the example in the wiki might be inaccurate as it doesn't include file extensions (https://github.com/tyiannak/pyAudioAnalysis/wiki/4.-Classification-and-Regression#train-regression-models-for-audio-segments).

Thanks so much for the support!
