### ISSUE TITLE
Audio segment Duration

### ISSUE THREAD

**Issue by CecchinLemos** [tyiannak/pyAudioAnalysis#192]
Is possible to get the segment duration using the mtFileClassification?

**Comment by tyiannak** [comment]
Segment duration is an argument to mtFileClassification (mtWin)
Unless u mean the signals total duration, which u can get by dividing its length by Fs.

**Comment by CecchinLemos** [comment]
Hi, thanks for the answer!
I discovered that flagsInd length is the total duration in seconds,  so the couting numbers inside flagsInd is possible to get the segment duration
`print(flagsInd)`

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.])
`
#segment1
print(flagsInd.sum())
#segment2
print(len(flagsInd[flagsInd<1]))
`
will returns 
69.0
96
