### ISSUE TITLE
UnpicklingError: unpickling stack underflow

### ISSUE THREAD

**Issue by zhengqun** [tyiannak/pyAudioAnalysis#205]
when i exec svm5classes,i met this issue.
could you help me ?
i use my own datasets(chinese)

**Comment by NSaviour** [comment]
> when i exec svm5classes,i met this issue.
> could you help me ?
> i use my own datasets(chinese)

你好，我在使用这个包的时候也遇到了同样的问题，想请教你后来是怎么解决的？

我尝试直接加载git上下载的svm5classes文件，报错：unpickling stack underflow

**Comment by NSaviour** [comment]
Hello, I have encountered the same problem when using this package. Could you tell me how to solve it.
I tried to load the file “svm5classes ”directly, and the error: unpickling stack underflow
