### ISSUE TITLE
quantity of samples required for a good model

### ISSUE THREAD

**Issue by Mario0606** [tyiannak/pyAudioAnalysis#213]
I have a question about the amount of data needed for a good model, contextualizing, I want the model to classify audios between yes or no, I currently have 30 audios (15 yes and 15 no) of distinct people, however my hit percentage is extremely low, I would like to know if it is really because of the quantity or if it is by the quality of the sounds, if by quantity, how many would you recommend me? 100, 200, 1000 or more? Would it be better to select 2 or 3 audios from each person or select only 1 even as it is now?

**Comment by tyiannak** [comment]
30 training samples for a binary classification task should reach a satisfactory performance (>80%). Ofcourse having more samples (at least 100) would make more sense. Also, don't forget that the correct cross-validation procedure should also take the speaker IDs into consideration.

**Comment by Mario0606** [comment]
Thanks for the response, my sorter is having a good hit now.
