### ISSUE TITLE
Speaker Diarization using live data

### ISSUE THREAD

**Issue by dkaushik95** [tyiannak/pyAudioAnalysis#217]
Hi,

I would love to have speaker diarization where I am providing data using a stream (Example using a microphone from a front-end server). Is there something to support this? 

Thanks.

**Comment by tyiannak** [comment]
Hi. Speaker diarization is already e very hard problem and the implementation supported in this library is quite "baseline": extraction of basic low level audio descriptors (features) followed by a standard kmeans clustering step. Transferring this pipeline in an "online" and "streaming" rationale would require an incremental implementation of the clustering step which is not straightforward and certainly not supported by this lib.

**Comment by dkaushik95** [comment]
Thanks for replying. pyAudioAnalysis is working great with a pretty accurate diarization. Hopefully, we get a better solution to this. Maybe something like [this](https://ieeexplore.ieee.org/document/6163887) incorporated into pyAudioAnalysis. 

Thanks for the work.
