### ISSUE TITLE
Query in stChromFeatures

### ISSUE THREAD

**Issue by MerinS** [tyiannak/pyAudioAnalysis#22]
In here --> 
https://github.com/tyiannak/pyAudioAnalysis/blob/master/audioFeatureExtraction.py#L267
The audio spectral values are divided by a scalar after they are pushed into the chroma audio bins.Could you let me know why that is done? 
If it is for some kind of normalization, could you elucidate what normalization it is, as it is not clear to me.

**Comment by tyiannak** [comment]
The extracted chroma values are normalized by the number of freq bins corresponding to each chroma bin. This is done so that the chroma values are not biased the spectral window size

**Comment by MerinS** [comment]
<First up, the second line isn't clear to me>
Also, shouldn't such a normalization be done at the end after the 2-D chroma array(12,X dimensions)is compiled to 1D(12)
Taking an instance when the window size - 512. There are 10 frequency elements in the Ab chroma bin, but the Chroma[8] value is divided by 3 though it is in Ab. Also chroma[20] is divided by 4 though it is in Ab as well. Please clarify why these differences occur.
