### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by AhmedHamedTN** [tyiannak/pyAudioAnalysis#23]
When dealing with **voiced audio**, can we conclude that if the number of segments is **n** for example then the number of pauses is **n - 1**  ?

**Comment by tyiannak** [comment]
This depends on the application domain: what does "segment" mean for you? A separate speaker? A word? A vowel? Also, it is not always necessary that there are pauses between two successive segments (e.g. there may be an overlap between two successive segments of speech and music).
