### ISSUE TITLE
NameError in pyAudioAnalysis/audioFeatureExtraction.py

### ISSUE THREAD

**Issue by VSydorskyy** [tyiannak/pyAudioAnalysis#249]
![Screenshot from 2019-11-01 14-54-57](https://user-images.githubusercontent.com/25751268/68026253-cbcdfd00-fcb7-11e9-8a91-71d971d3ae35.png)

**Comment by duarteocarmo** [comment]
There is a typo right [here](https://github.com/tyiannak/pyAudioAnalysis/blob/master/pyAudioAnalysis/audioFeatureExtraction.py#L171). 

Just replace `linc` by `linsc`

**Comment by duarteocarmo** [comment]
And create a PR while you are at it :smile:

**Comment by VSydorskyy** [comment]
As I understood, you have fixed it. Thanks
