### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by piuskavz** [tyiannak/pyAudioAnalysis#255]
Hi, I am trying to run classification on a single wav file using python3.6 as follows:
python3.6 ../pyAudioAnalysis/pyAudioAnalysis/audioAnalysis.py classifyFile -i ../file.wav --model svm --classifier ../pyAudioAnalysis/pyAudioAnalysis/data/svmSM

I get the following Traceback:
../.local/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator SVC from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Class	Probability
Traceback (most recent call last):
  File "/home/radio/radio/new_scripts/pyAudioAnalysis/pyAudioAnalysis/audioAnalysis.py", line 573, in <module>
    classifyFileWrapper(args.input, args.model, args.classifier)
  File "/home/radio/radio/new_scripts/pyAudioAnalysis/pyAudioAnalysis/audioAnalysis.py", line 105, in classifyFileWrapper
    for i, c in enumerate(classNames):
TypeError: 'int' object is not iterable

**Comment by piuskavz** [comment]
The error was due to the function returning an int instead of a list. This was all due to a raw file from  GNU SDR that was erroneously labeled as .wav, so the function kept returning the values -1, -1, -1

**Comment by mangomadhava** [comment]
Was there a solution to this that was posted?
