### ISSUE TITLE
mlpy has no attribute 'LibSvm'

### ISSUE THREAD

**Issue by yangzhi-psy** [tyiannak/pyAudioAnalysis#26]
Fedora21 x86_64
python 2.7.12, Anaconda 4.1.1
downloaded and installed mlpy-3.5.0 as instructed.
When testing silence segmentation, got the following error:

>>> segments = aS.silenceRemoval(x, Fs, 0.020, 0.020, smoothWindow = 1.0, Weight = 0.3, plot = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yangz2/libs/pyAudioAnalysis/audioSegmentation.py", line 567, in silenceRemoval
    SVM = aT.trainSVM(featuresNormSS, 1.0)                               # train the respective SVM probabilistic model (ONSET vs SILENCE)
  File "/home/yangz2/libs/pyAudioAnalysis/audioTrainTest.py", line 165, in trainSVM
    svm = mlpy.LibSvm(svm_type='c_svc', kernel_type='linear', eps=0.0000001, C=Cparam, probability=True)
AttributeError: 'module' object has no attribute 'LibSvm'

**Comment by tyiannak** [comment]
You probably have another mlpy version in parallel (maybe you've installed it in the past using apt-get install or pip).

**Comment by tyiannak** [comment]
Update: the latest pyAudioAnalysis version (8.9.2016) does not have mlpy as a dependency.  It only requires scikit-learn for (un)supervised learning
