### ISSUE TITLE
Matplotlib error

### ISSUE THREAD

**Issue by SerjSmor** [tyiannak/pyAudioAnalysis#264]
Running the following example: 
```
from pyAudioAnalysis import audioBasicIO
from pyAudioAnalysis import ShortTermFeatures
import matplotlib.pyplot as plt
[Fs, x] = audioBasicIO.read_audio_file("pyAudioAnalysis/data/scottish.wav")

F, f_names = ShortTermFeatures.feature_extraction(x, Fs, 0.050*Fs, 0.025*Fs)
plt.subplot(2,1,1); plt.plot(F[0,:]); plt.xlabel('Frame no'); plt.ylabel(f_names[0]) 
plt.subplot(2,1,2); plt.plot(F[1,:]); plt.xlabel('Frame no'); plt.ylabel(f_names[1]); plt.show()
```

Produced this error: 
AttributeError: module 'matplotlib' has no attribute 'colors'

Full stack: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-1ad72c5004cb> in <module>
     22 F, f_names = ShortTermFeatures.feature_extraction(x, Fs, 0.050*Fs, 0.025*Fs)
     23 plt.subplot(2,1,1); plt.plot(F[0,:]); plt.xlabel('Frame no'); plt.ylabel(f_names[0])
---> 24 plt.subplot(2,1,2); plt.plot(F[1,:]); plt.xlabel('Frame no'); plt.ylabel(f_names[1]); plt.show()
     25 
     26 # !python audioAnalysis.py segmentClassifyFile -i <inputFile> --model <model type (svm or knn)> --modelName <path to classifier model>

~/anaconda3/envs/audio3.6/lib/python3.6/site-packages/matplotlib/pyplot.py in show(*args, **kw)
    250     """
    251     global _show
--> 252     return _show(*args, **kw)
    253 
    254 

~/anaconda3/envs/audio3.6/lib/python3.6/site-packages/ipykernel/pylab/backend_inline.py in show(close, block)
     37             display(
     38                 figure_manager.canvas.figure,
---> 39                 metadata=_fetch_figure_metadata(figure_manager.canvas.figure)
     40             )
     41     finally:

~/anaconda3/envs/audio3.6/lib/python3.6/site-packages/ipykernel/pylab/backend_inline.py in _fetch_figure_metadata(fig)
    172     """Get some metadata to help with displaying a figure."""
    173     # determine if a background is needed for legibility
--> 174     if _is_transparent(fig.get_facecolor()):
    175         # the background is transparent
    176         ticksLight = _is_light([label.get_color()

~/anaconda3/envs/audio3.6/lib/python3.6/site-packages/ipykernel/pylab/backend_inline.py in _is_transparent(color)
    193 def _is_transparent(color):
    194     """Determine transparency from alpha."""
--> 195     rgba = colors.to_rgba(color)
    196     return rgba[3] < .5

AttributeError: module 'matplotlib.colors' has no attribute 'to_rgba'

**Comment by mdinescu** [comment]
That is likely because you have an older version of matplotlib installed. Try updating matplotlib:

```
pip install --upgrade matplotlib
```

Also -- out of curiosity, what version of matplotlib do you have installed?

**Comment by DerekChia** [comment]
Perhaps it's time to update the `requirements.txt`? Currently it is pinned to version `1.5.3`...

```
numpy
matplotlib==1.5.3
scipy
sklearn
hmmlearn
simplejson
eyed3
pydub
```

**Comment by tyiannak** [comment]
Thanx guys, I've already updated the reqs file.
