### ISSUE TITLE
help required in understanding the code?

### ISSUE THREAD

**Issue by praveen5655** [tyiannak/pyAudioAnalysis#269]
I want to try couple of experiments using this. So I need help in understanding the results 
i.e.: (0.0, array([ 0.90156761,  0.09843239]), ['music', 'speech']) ??
I am unable to understand the result of what does 0.0 representing?
array([0.0901,0.098]) represent?
['music'.'speech']??
and how do I train it and extract the results?

**Comment by tyiannak** [comment]
These are: winner class, posteriors of the two classes, and list of classes names returned by the classification functions. (please read the wiki before posting)
