### ISSUE TITLE
More API doc

### ISSUE THREAD

**Issue by bobonovski** [tyiannak/pyAudioAnalysis#27]
Hello, Theodoros,
This library is awesome, but I can't find any doc for the api, for example the meaning of parameters and how to tune them?

Thanks

**Comment by tyiannak** [comment]
Hi.
The wiki contains some details on the individual methods and respective params (https://github.com/tyiannak/pyAudioAnalysis/wiki).
Also, please see http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0144610 for more general and algorithmic info.
