### ISSUE TITLE
Out of date wiki 

### ISSUE THREAD

**Issue by HPrickettMorgan** [tyiannak/pyAudioAnalysis#270]
On the [segmentation wiki page](https://github.com/tyiannak/pyAudioAnalysis/wiki/5.-Segmentation), there are code examples which seem to be from an earlier version (pre-refactoring).

To bring these up to date, references to the following functions should be updated
1. `mtFileClassification()` -> `mid_term_file_classification()`
2. `mtFeatureExtraction()` -> `mid_feature_extraction()`
3. `trainHMM_fromFile ` -> `train_hmm_from_file()`
4. `trainHMM_fromDir` -> `train_hmm_from_dir()`
5. `hmmSegmentation()` -> `hmm_segmentation()`
6. `evaluateSegmentationClassificationDir()` -> `evaluate_segmentation_classification_dir()`
7. `aS.silenceRemoval(x, Fs, 0.020, 0.020, smoothWindow = 1.0, Weight = 0.3, plot = True)` -> `segments = aS.silence_removal(x, Fs, 0.020, 0.020, smooth_window = 1.0, weight = 0.3, plot = True)

I may have missed a couple. I would have PRed but it seems like I can't for wiki pages. Great library!

**Comment by mchen0037** [comment]
I'm also having trouble using mid_term_file_classification.

When using the example in the wiki (edited to)
```
[flagsInd, classesAll, acc, CM] = aS.mid_term_file_classification("data/scottish.wav", "data/svmSM", "svm", True, 'data/scottish.segments')
```
I get back 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mighty/cecl/tests/pyAudioAnalysis/pyAudioAnalysis/audioSegmentation.py", line 580, in mid_term_file_classification
    feature_vector = (mt_feats[:, col_index] - mean) / std
ValueError: operands could not be broadcast together with shapes (136,) (68,) 

Do you get the same error @HPrickettMorgan?

**Comment by HPrickettMorgan** [comment]
@mchen0037 I wasn't using that part of the library, can only confirm that silence removal works as expected with those changes.

**Comment by tyiannak** [comment]
Thank you @HPrickettMorgan for the comment I will update the wiki ASAP.\
Thank you @mchen0037 indeed the instructions need to be updated. Btw the models are stored in data/models now and I had to delete data/svmSM... So your example should work like this:
`from pyAudioAnalysis import audioSegmentation as aS
[flagsInd, classesAll, acc, CM] = aS.mid_term_file_classification("data/scottish.wav", "data/models/svm_rbf_sm", "svm", True, 'data/scottish.segments')`
(btw pls pull cause there was a minor bug in the evaluation function)

**Comment by maggie0830** [comment]
>>> from pyAudioAnalysis import audioSegmentation as aS
>>> [flagsInd, classesAll, acc, CM] = aS.mid_term_file_classification("data/scottish.wav", "data/models/svm_rbf_sm", "svm", True, 'data/scottish.segments')
mtFileClassificationError: input model_type not found!
