### ISSUE TITLE
ERROR: invalid delimiter in diarizationExample.segments 

### ISSUE THREAD

**Issue by pelgray** [tyiannak/pyAudioAnalysis#271]
The delimiter was changed to 'tab' in the commit: https://github.com/tyiannak/pyAudioAnalysis/commit/391e269a923e2d3abaccde2b7e6a3afc9793cc09
https://github.com/tyiannak/pyAudioAnalysis/blob/391e269a923e2d3abaccde2b7e6a3afc9793cc09/pyAudioAnalysis/data/diarizationExample.segments#L1

But parser doesn't support it; https://github.com/tyiannak/pyAudioAnalysis/blob/5b333d9bd8e3c8e36e7339a94c2d51bf22d09b38/pyAudioAnalysis/audioSegmentation.py#L161

**Comment by tyiannak** [comment]
Thanx @pelgray 
in https://github.com/tyiannak/pyAudioAnalysis/commit/a7dbf4a6b3bb3b2d5169be419471dd4fd0872ee1 all .segment files have been changed so that delimiter is tab instead of comma.
Also line 161 has changed.
