### ISSUE TITLE
Error: unknown file type {extension}

### ISSUE THREAD

**Issue by maggie0830** [tyiannak/pyAudioAnalysis#273]
on the terminal, python3   enter,   when I "from pyAudioAnalysis import audioTrainTest as aT" 
>>> from pyAudioAnalysis import audioTrainTest as aT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gongyunmei/pyAudioAnalysis/pyAudioAnalysis/audioTrainTest.py", line 10, in <module>
    from pyAudioAnalysis import MidTermFeatures as aF
  File "/home/gongyunmei/pyAudioAnalysis/pyAudioAnalysis/MidTermFeatures.py", line 8, in <module>
    from pyAudioAnalysis import audioBasicIO
  File "/home/gongyunmei/pyAudioAnalysis/pyAudioAnalysis/audioBasicIO.py", line 100
    print(f"Error: unknown file type {extension}")
                                                ^
SyntaxError: invalid syntax

I don't known  the reseason.   Before that, I run all the code on the python2, all is ok, and no error happened, thanks

**Comment by maggie0830** [comment]
I know the reseason : the original code error, and line 100 in the audioBasicIO.py, modify the print(f"Error: unknown file type {extension}") to print("Error: unknown file type {extension}").  There an character "f" in the code.

**Comment by tyiannak** [comment]
Fixed in the latest commit (https://github.com/tyiannak/pyAudioAnalysis/commit/3de4dcf1702bf5fe8de4930811e9f7025db40b75)
