### ISSUE TITLE
Valence/Arousal tagged file for Emotion Regression

### ISSUE THREAD

**Issue by jyoti59n** [tyiannak/pyAudioAnalysis#29]
I don't find the 2 files valence.csv & arousal.csv for SVR training. Could you kindly help me with the path to access those files? Thanks.

**Comment by tanjosh** [comment]
Same here

**Comment by marcodemata** [comment]
i have the same problem...help me please...

**Comment by tyiannak** [comment]
Sorry for the delay.
I must have accidentaly removed the two files.
They are online now (in data/speechEmotion)
