### ISSUE TITLE
ShortTermFeatures.feature_extraction returns 68 features not 34

### ISSUE THREAD

**Issue by txntxn** [tyiannak/pyAudioAnalysis#295]
According to the wiki https://github.com/tyiannak/pyAudioAnalysis/wiki/3.-Feature-Extraction, "eature_extraction() returns a numpy matrix of 34 rows and N columns, where N is the number of short-term frames that fit into the input audio recording."

However, I am getting 68 features, even tho my audio is mono:

```
from pyAudioAnalysis import audioBasicIO
from pyAudioAnalysis import ShortTermFeatures

def pAA(filename):
    [Fs, x] = audioBasicIO.read_audio_file(filename)
    x = audioBasicIO.stereo_to_mono(x)
    # The following code uses feature_extraction() of the ShortTermFeatures.py file to extract the short term
    # feature sequences for an audio signal, using a frame size of 50 msecs and a frame step of 25 msecs
    # (50% overlap).
    F, f_names = ShortTermFeatures.feature_extraction(x, Fs, 0.050*Fs, 0.025*Fs)
    return F

pAA("VARIATION-004-024.mp3").shape
```
(68, 99)

Why? The last 34 features are delta features, perhaps these should be documented?

When would you need them?

**Comment by xiaoyuan1996** [comment]
All of these 
++++++++++++++++++++++++++++++++++++++++++++
zcr
energy
energy_entropy
spectral_centroid
spectral_spread
spectral_entropy
spectral_flux
spectral_rolloff
mfcc_1
mfcc_2
mfcc_3
mfcc_4
mfcc_5
mfcc_6
mfcc_7
mfcc_8
mfcc_9
mfcc_10
mfcc_11
mfcc_12
mfcc_13
chroma_1
chroma_2
chroma_3
chroma_4
chroma_5
chroma_6
chroma_7
chroma_8
chroma_9
chroma_10
chroma_11
chroma_12
chroma_std
delta zcr
delta energy
delta energy_entropy
delta spectral_centroid
delta spectral_spread
delta spectral_entropy
delta spectral_flux
delta spectral_rolloff
delta mfcc_1
delta mfcc_2
delta mfcc_3
delta mfcc_4
delta mfcc_5
delta mfcc_6
delta mfcc_7
delta mfcc_8
delta mfcc_9
delta mfcc_10
delta mfcc_11
delta mfcc_12
delta mfcc_13
delta chroma_1
delta chroma_2
delta chroma_3
delta chroma_4
delta chroma_5
delta chroma_6
delta chroma_7
delta chroma_8
delta chroma_9
delta chroma_10
delta chroma_11
delta chroma_12
delta chroma_std
++++++++++++++++++++++++++++++++++++++++++++
so I think maybe the author add 34 delta_* in the last.

**Comment by tyiannak** [comment]
Thanx for the comment, i've updated the wiki
"The total number of short-term features implemented in pyAudioAnalysis is 34. In addition, the delta features are optionally computed (they are by default enabled, but can be disabled by setting the deltas argument in feature_extraction() to false). So, the total number of short-term features, including the deltas is 64."
