### ISSUE TITLE
About regression and valence-arousal values

### ISSUE THREAD

**Issue by anastasiaTesla** [tyiannak/pyAudioAnalysis#3]
Hello,
first thank you very much about this project, hope it will be helpful in my diploma thesis!
I would like to clarify something about the value ranges of valence and arousal and svr.
What values I am supposed to input for ground truth?
What are their range? From the wiki I would guess they should vary in the [-1,1] interval but I'm not very sure. 

Thank you in advance,
Anastasia

**Comment by tyiannak** [comment]
Dear Anastasia,
Thank you for your interest. This is a regression task, therefore, any
value will do. In this particular example the output value range is indeed
-1..1.
Regards,
Theodore
