### ISSUE TITLE
Wiki Outdated Functions

### ISSUE THREAD

**Issue by markwu2001** [tyiannak/pyAudioAnalysis#300]
When testing the code here, I found that the function names (and parameters) are outdated. Not sure if this is an issue in other parts of the wiki. The correct function names have underscores and are not in camelCase.

https://github.com/tyiannak/pyAudioAnalysis/wiki/5.-Segmentation#silence-removal-and-event-detection
from pyAudioAnalysis import audioBasicIO as aIO
from pyAudioAnalysis import audioSegmentation as aS
[Fs, x] = aIO.**readAudioFile**("data/recording1.wav")
segments = aS.silence_removal(x, Fs, 0.020, 0.020, **smoothWindow** = 1.0, **Weight** = 0.3, plot = True)

correct functions:
[Fs, x] = aIO.**read_audio_file**("data/recording1.wav")
segments = aS.silence_removal(x, Fs, 0.020, 0.020, **smooth_window** = 1.0, **weight** = 0.3, plot = True)

**Comment by vybhav72954** [comment]
There are similar mismatches in various parts of Wiki. @tyiannak You guys need to edit the Wiki sooner or later.

**Comment by tyiannak** [comment]
Yes i thought I had changed all references to functions from camelCase to underscore format, but is seems some are still missing. Anyway, I did some more fixes in wikis 4 and 5 mostly, hope it is ok now
