### ISSUE TITLE
Probably incorrect calculation of window ratio in mid_feature_extraction()

### ISSUE THREAD

**Issue by tluocs** [tyiannak/pyAudioAnalysis#306]
It seems that the `mid_feature_extraction()`, as in the `MidTermFeatures` module, contains an error in computing the ratio between the mid-term window and the short-term window. Details below.

`def mid_feature_extraction(signal, sampling_rate, mid_window, mid_step,
                           short_window, short_step):`
`...` 
`mid_window_ratio = int(round(mid_window / short_step))`

I think the above line (Line 96) should be corrected to:
`mid_window_ratio = round( (mid_window - (short_window - short_step)) / short_step )`

**Comment by tyiannak** [comment]
Thanx indeed there were some more short-term windows included in the mid-sized segments, in case short-term window length was > short-term window step (overlapping short-term frames case)

Fixed in https://github.com/tyiannak/pyAudioAnalysis/commit/f7f170daffb51a2f83eef0dd4a6c31e075b49dfe
