### ISSUE TITLE
Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning) 

### ISSUE THREAD

**Issue by lxrswdd** [tyiannak/pyAudioAnalysis#314]
This happens when I run  'from pyAudioAnalysis import audioTrainTest as aT'
I have done 'pip install ffmpeg''' but it did not help.

Can anyone help me?
Thanks

**Comment by tyiannak** [comment]
You will need to install ffmpeg (e.g. sudo apt-get install ffmpeg in linux)

**Comment by lxrswdd** [comment]
> You will need to install ffmpeg (e.g. sudo apt-get install ffmpeg in linux)

I am running on a Linux server based on Centos so I cannot do     `sudo apt install ffmpeg.`
Therefore I have tried to clone the package into my folder and tried to run `./configure` as following the installation steps. However, ./configure shows permission denied so I tried `sudo ./configure` which shows command not found...

I also tried to follow the instruction from https://www.vultr.com/docs/how-to-install-ffmpeg-on-centos   which popped up a lot of Errors.

**Comment by lxrswdd** [comment]
I fixed it as it was due to the  authority problem in the system
