### ISSUE TITLE
bug in PLOT of stChromagram()

### ISSUE THREAD

**Issue by jmw67** [tyiannak/pyAudioAnalysis#32]
Hi,
you should add the following line after the Ratio calculation : 
Ratio = chromaGramToPlot.shape[1] / (3*chromaGramToPlot.shape[0])
if Ratio < 1 : Ratio=1

I had Ratio equal to 0 that created problems with range afterwards.
best regards

**Comment by tyiannak** [comment]
Thank you, so much.
Change committed in master.
