### ISSUE TITLE
Matplotlib Error while trying silence removal

### ISSUE THREAD

**Issue by BeardyMan37** [tyiannak/pyAudioAnalysis#336]
Matplotlib error of **ValueError: x and y must have same first dimension, but have shapes (122,) and (121,)** occurs when trying out silence removal. I had to comment out [line 788 of audioSegmentation.py](https://github.com/tyiannak/pyAudioAnalysis/blob/b27644a3d9351733693c79718441430619d6141f/pyAudioAnalysis/audioSegmentation.py#L788) to get the code working. After commenting it out, I got the code working, but I couldn't see the '**svm Probability**' graph.

**Comment by tyiannak** [comment]
Can u share a sample audio file that reproduces the error? it seems to work with a couple of audio files I've tested.

**Comment by BeardyMan37** [comment]
Issue resolved. I was passing different lengthened audio clips.
