### ISSUE TITLE
How to setting up pyAudioAnalysis

### ISSUE THREAD

**Issue by xtreme25711** [tyiannak/pyAudioAnalysis#34]
I am new to Raspberry Pi (Raspbian), I have successfully installed all the dependancies, now i am trying the sample codes that provided by pyAudioAnalysis, when I run the codes, the system shows ImportError: No module name pyAudioAnalysis. which i dont understand that python path steps. can anyone teach me? I have added export PYTHONPATH=$PYTHONPATH:"/home/pi" in the .bashrc file, but i dont understand about update the path details which is source ~/.bashrc .........may i know where  to type soruce ~/.bashrc???

**Comment by tyiannak** [comment]
have u placed the library in the /home/pi folder?
you just type  source ~/.bashrc in any terminal

**Comment by xtreme25711** [comment]
yes.. my library is in the /home/pi folder already...... i have also typed "source /.bashrc" in my raspberry pi terminal... but when i run the code in python... python still cant detect the library...

**Comment by mansooralam** [comment]
In `~/.bashrc`, you will want to add the full path to the `pyAudioAnalysis` directory.

So if the directory is located in `/home/pyAudioAnalysis`, add the following line to your `~/.bashrc` file:

`export PATH="/home/pyAudioAnalysis/:$PATH" `

Then try running `source ~/.bashrc` again.

**Comment by tyiannak** [comment]
in which path have u cloned pyAudioAnalysis exactly?
