### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by qkum** [tyiannak/pyAudioAnalysis#366]
Command:
`python audioAnalysis.py segmentClassifyFile -i data/scottish.wav --model svm --modelName data/models/svm_rbf_sm`

Output:
`ModuleNotFoundError: No module named 'pandas'`

Pandas is not part of the requirements.txt file.

Please update `requirements.txt`

Possible fix:
`pip install pandas`

Ok, that leads to dependency version problems.

The fix may be to downgrade from Python 3.8.

Update: 

Ok, Python 3.6, 3.7 give the same problems.

It may be a better use of my time to find something that is up to date....many dependencies are missing and the versions are right and left. Not even the foundation of the correct Python version we know...

**Comment by tyiannak** [comment]
please check the latest requirements.txt. Works in Python 3.8 and 3.9
