### ISSUE TITLE
Add FFT function to FeatureExtraction

### ISSUE THREAD

**Issue by jhoelzl** [tyiannak/pyAudioAnalysis#39]
Since the frequency domain features in https://github.com/tyiannak/pyAudioAnalysis/blob/master/audioFeatureExtraction.py expect `abs(fft)` of the frame as input value, it would be nice to also provide a FFT function in this library.

Thanks!

**Comment by GovertJaap** [comment]
An FFT function should be imported from `scipy.fftpack`, at the top of the audioFeatureExtraction.py file, make sure you have imported that.

**Comment by jhoelzl** [comment]
Ah, i see, thanks!

So, when computing features in frequency domain, i use this as input data:

`abs(fft(x))`
