### ISSUE TITLE
writeTrainDataToARFF(), tuple index out of range, 

### ISSUE THREAD

**Issue by GovertJaap** [tyiannak/pyAudioAnalysis#40]
So I am trying to make a rudimentary emotion classifier, and I have collected a small datasample to test if it works. my code is as following:

`aA.trainClassifierWrapper('svm', False,
                      ["C:\Users\gover_000\Desktop\Angry",
                      "C:\Users\gover_000\Desktop\Happy",
                      "C:\Users\gover_000\Desktop\Sad",
                      "C:\Users\gover_000\Desktop\Scared",
                      "C:\Users\gover_000\Desktop\Neutral"],
                      "testSVM")`

If I execute this, it gives this error: 

`IndexError                                Traceback (most recent call last)`
`<ipython-input-7-2e5393432e89> in <module>()`
`          5                       "C:\Users\gover_000\Desktop\Scared",`
 `         6                       "C:\Users\gover_000\Desktop\Neutral"],`
`    ----> 7                       "testSVM")`

`C:\Users\gover_000\Documents\GitHub\Emotion-Recognition-Prototype\pyAudioAnalysis\audioAnalysis.pyc in trainClassifierWrapper(method, beatFeatures, directories, modelName)`
`     88         raise Exception("At least 2 directories are needed")`
`    89     aT.featureAndTrain(directories, 1, 1, aT.shortTermWindow, aT.shortTermStep,`
`---> 90                        method.lower(), modelName, computeBEAT=beatFeatures)`

`C:\Users\gover_000\Documents\GitHub\Emotion-Recognition-Prototype\pyAudioAnalysis\audioTrainTest.pyc in featureAndTrain(listOfDirs, mtWin, mtStep, stWin, stStep, classifierType, modelName, computeBEAT, perTrain)`
`    275     featureNames = ["features" + str(d + 1) for d in range(numOfFeatures)]`
`    276 `
`--> 277     writeTrainDataToARFF(modelName, features, classNames, featureNames)`

`C:\Users\gover_000\Documents\GitHub\Emotion-Recognition-Prototype\pyAudioAnalysis\audioTrainTest.pyc in writeTrainDataToARFF(modelName, features, classNames, featureNames)`
`   1097     for c, fe in enumerate(features):`
`   1098         for i in range(fe.shape[0]):`
`-> 1099             for j in range(fe.shape[1]):`
`   1100                 f.write("{0:f},".format(fe[i, j]))`
`   1101             f.write(classNames[c]+"\n")`

`IndexError: tuple index out of range`

I know  `shape[1]` is supposed to return the columns of an array dimension. 
but why does it return an error here

**Comment by rahulshankar02** [comment]
I am new to python, and I might be wrong but I was faced with the same issue. In my case, what fixed the issue were ensuring the following conditions:
1) The training files are in the .wav format and are stereo files
2) Atleast two files are used to train your classifier

Hope this helps!

**Comment by GovertJaap** [comment]
Thank you! I thought you had to have 2 files at least in total, it appears you have to have two files per class. that fixed the issue!
