### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by stuaxo** [tyiannak/pyAudioAnalysis#43]
This could probably do with a setup.py.

To make this work, everything should be moved into a subdirectory.

Is there a prefered way to install pyAudioAnalysis currently ?

**Comment by jhoelzl** [comment]
Hello, i have already made a pull request for this issue: #38

**Comment by stuaxo** [comment]
Looks like there is a conflict, maybe a file got edited after you renamed it on master?

**Comment by jhoelzl** [comment]
Yes, this commit: https://github.com/tyiannak/pyAudioAnalysis/commit/6f64dffeaaea6f1a8e23403dcafda173c31328ab

**Comment by keunwoochoi** [comment]
No further plan on this?

**Comment by jhoelzl** [comment]
+1

**Comment by stuaxo** [comment]
It looks like it wouldn't be too difficult to update so that it doesn't clash with the other commit.

Unhelpfully, I don't have the time right now myself :)

**Comment by keunwoochoi** [comment]
It's a simple task, but I believe it should be done by the owner.
