### ISSUE TITLE
npy_logl undefined error .

### ISSUE THREAD

**Issue by jacoblukose** [tyiannak/pyAudioAnalysis#48]
![error](https://cloud.githubusercontent.com/assets/7311003/20714683/c06872d0-b672-11e6-9425-4e19bd8a4655.png)

How to resolve this issue ? 

ImportError: /usr/local/lib/python2.7/dist-packages/hmmlearn/_hmmc.so: undefined symbol: npy_logl

**Comment by WGierke** [comment]
can confirm

**Comment by WGierke** [comment]
Reinstalling hmmlearn worked for me (https://github.com/hmmlearn/hmmlearn/issues/160)

**Comment by nicolaspanel** [comment]
you may also need to upgrade numpy:
```
pip uninstall hmmlearn
pip install -U numpy
pip install  --no-cache-dir hmmlearn 
```
