### ISSUE TITLE
sklearn.hmm deprecated

### ISSUE THREAD

**Issue by mazdaebrahimi** [tyiannak/pyAudioAnalysis#5]
Hi, It looks like sklearn.hmm is deprecated.
I tried using hmmlearn instead, but get this error:
"This GaussianHMM instance is not fitted yet. Call 'fit' with appropriate arguments before using this method."

**Comment by irisyupingren** [comment]
Same here. Can't load hmm

**Comment by mazdaebrahimi** [comment]
I reverted back to an older version of sklearn and was able to get it running

**Comment by fooqri** [comment]
Thanks for the note, specifically python 2 with scikit-learn v0.16.1 worked for me.
