### ISSUE TITLE
how to print (or export) diarization data

### ISSUE THREAD

**Issue by mosherayman** [tyiannak/pyAudioAnalysis#54]
I see how to run the diarization sample which displays the plot on the screen.

How can I export segmentation data for diarization, where each segment starts and who the speaker is.

thanks

**Comment by mosherayman** [comment]
i got it, use flags2segs

**Comment by simonnarang** [comment]
We should probably put this in the wiki it looks like a lot of people are/were confused about this

**Comment by ossim** [comment]
Could I get a bit of clarification on how to use flags2segs to generate the diarization output as a file in the demo?

**Comment by mosherayman** [comment]
If cls is the output of some segmentation function in "flags" format (e.g. SpeakerDiarization), and you want to convert it into segmentation format, use the following code
```
     segs,flags = flags2segs(cls, mtStep)     
     for s in range(segs.shape[0]):
         print "{} {} {}\n".format(segs[s,0], segs[s,1], flags[s])
```
the mtStep value should be the one you passed to the SpeakerDiarization function.

I hope this helps
