### ISSUE TITLE
analyzeMovieSound Example

### ISSUE THREAD

**Issue by ThomasLengeling** [tyiannak/pyAudioAnalysis#60]
Hello, I am wondering if there is any example use of the analyzeMovieSound code?
I want to extract audio from a video file and do several operations on it such as segmentation(speech, music, silence), and feature detection.
I appreciate your help.

**Comment by tyiannak** [comment]
Hi. This file will be removed in the feature as it just contains calls to pyAudioAnalysis and some wrappers for multiple file analysis etc. You can use the rest of the functionalities described in the wiki for segmentation/classification.
