### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by rcbyron** [tyiannak/pyAudioAnalysis#7]
The Scikits.Talkbox module seems to only work on Python 2.7.

Is there a way that I can use this software on Python 3.3 and above?

**Comment by tyiannak** [comment]
Hi. The whole library has only been tested in Python 2.7

**Comment by astromme** [comment]
Perhaps this should be left open as a feature request? Also would be useful to note that Python 2.7 is supported on the README.md. Thanks!

**Comment by onsunsl** [comment]
Hope to provide python3 version, thanks

**Comment by jhoelzl** [comment]
i could change the code to work with python3. However, i assume it is not backwards compatible to Python 2.7.  But this is not a crucial task, i think the author could do this as he do not accepts pull requests.
