### ISSUE TITLE
empty array or plot axis dimension mismatch in silenceRemovel()

### ISSUE THREAD

**Issue by MJ-Piano** [tyiannak/pyAudioAnalysis#77]
Just remind in my test case, the following two lines will result in T1 or T2 nan if L1 is 0 or 1:
T1 = numpy.mean(E[0:L1]) + 0.000000000000001                 
T2 = numpy.mean(E[-L1:-1]) + 0.000000000000001 
we can solve this according to the value of L1.

The plot will fail due to mismatch dimension in the following line of code:
plt.plot(numpy.arange(0, ProbOnset.shape[0] * stStep, stStep), ProbOnset)
I solved this by the following:
plt.plot(numpy.arange(0, ProbOnset.shape[0] * stStep - stStep/2, stStep), ProbOnset)

Thank you all the contributors for this wonderful tool.
Regards

**Comment by tyiannak** [comment]
Thanx alot for the info, I was not able to reproduce the problem, probably due to the particular st step I used.
