### ISSUE TITLE
How to export diarization data to a file?

### ISSUE THREAD

**Issue by ossim** [tyiannak/pyAudioAnalysis#87]
#54 addressed this briefly, to "use flags2segs" but I'm not sure where/when/how is the best way to put that function call. Could someone walk through what that process would look like?

**Comment by eyal13579** [comment]
also eager to understand that...

**Comment by mosherayman** [comment]
If cls is the output of some segmentation function in "flags" format (e.g. SpeakerDiarization), and you want to convert it into segmentation format, use the following code
  ```
       segs,flags = flags2segs(cls, mtStep)     
       for s in range(segs.shape[0]):
           print "{} {} {}\n".format(segs[s,0], segs[s,1], flags[s])
```
the mtStep value should be the one you passed to the SpeakerDiarization function.

I hope this helps

**Comment by ossim** [comment]
Sounds great, thanks for the help 👍

**Comment by Tortoise17** [comment]
Awesome help. Thank you guys. !!!
