### ISSUE TITLE
SyntaxError when trying to execute the Chroma example

### ISSUE THREAD

**Issue by denisb411** [tyiannak/pyAudioAnalysis#97]
I'm tried with both Python 2.7 and 3.6. Still getting this error:

![image](https://user-images.githubusercontent.com/13735079/28369030-b2522e24-6c6c-11e7-9ed6-83002cb6129b.png)

**Comment by jhoelzl** [comment]
I assume that the print statements in this library are not Python 3 compatible (brackets are missing).
